# Generated by Django 4.2.3 on 2023-07-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_teams',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(default='', max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
