GET http://localhost:8000/api/room


###

POST http://localhost:8000/api/create-room
Content-Type: application/json

{
    "username": "testname",
    "words_per_user": 5,
    "num_teams": 3
}

###

GET http://localhost:8000/api/get-room?code=YAKMYG

###

POST http://localhost:8000/api/join-room
Content-Type: application/json

{
    "username": "testname",
    "code": "YAKMYG"
}


###
POST http://localhost:8000/api/exit-room
Content-Type: application/json
